### ISSUE TITLE
Wrong Obfuscated Method Name for Furnace?

### ISSUE THREAD

**Issue by brisingraerowing** [thraaawn/ocsensors#11]
I noticed an error in the game output stating that the method isBurning could not be found (as expected), but right after it was an error stating that the obfuscated name you have in the configuration wasn't found. Looking at the MCP data it seems that isBurning maps to func_145950_i, which has the comment "Furnace isBurning". What you have also maps to an isBurning method, but that one has no comment.

**Comment by davenonymous** [comment]
Thanks for the report! That was indeed the wrong obfuscated method name.
