### ISSUE TITLE
[Curseforge] Mark as supporting 1.12.2

### ISSUE THREAD

**Issue by brisingraerowing** [thraaawn/ocsensors#8]
I use this mod on 1.12.2 on a manually created pack, and it works fine. But, since the download is not marked as 1.12.2 compatible the Twitch client will refuse to allow it in a 1.12.2 pack (like the skyblock one I am working on). Could it be marked as compatible?

**Comment by davenonymous** [comment]
Will do.

**Comment by davenonymous** [comment]
Done.

**Comment by brisingraerowing** [comment]
Thanks!
