### ISSUE TITLE
[Suggestion] Add ability to analyze entities

### ISSUE THREAD

**Issue by brisingraerowing** [thraaawn/ocsensors#9]
Being able to analyze entities (either with the current sensor or a new dedicated entity sensor) would be very useful in things like automated animal sorters (e.g. Sorting a mess of Cows / Pigs / Sheep / Chickens / Etc. from a passive mob farm into separate holding areas for processing or sorting Moo Fluids fluid cows by fluid into milking pens).

**Comment by davenonymous** [comment]
I will add this in the next release. Will probably be with the same block, but a new function.

**Comment by davenonymous** [comment]
This has been released and is waiting for approval on curse.
Have fun!

**Comment by brisingraerowing** [comment]
Thanks!
